/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yt.downloader;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.io.File;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;

@SpringBootApplication
public class App {

    public static ConfigManager configManager;
    public static String webpage;
    public static String style;
    public static String js;

    public static HashMap<String, Long> progress = new HashMap<>();


    public static void main(String[] args) {
        try {
            configManager = new ConfigManager();
        } catch (Exception e) { e.printStackTrace(); }

        for (String path : List.of("web/index.html", "web/styles.css", "web/app.js")) {
            File file = new File(path);
            if (file.exists()) {
                try (Scanner myReader = new Scanner(file)) {
                    StringBuilder stringBuilder = new StringBuilder();
                    while (myReader.hasNextLine()) {
                        stringBuilder.append(myReader.nextLine());
                    }
                    myReader.close();
                    if (path.endsWith(".js")) {
                        js = stringBuilder.toString();
                    } else if (path.endsWith(".css")){
                        style = stringBuilder.toString();
                    } else {
                        webpage = stringBuilder.toString();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                if (path.endsWith(".js")) {
                    js = "function updateDownloadProgress(percent) { document.getElementById(\"progress\").innerHTML = percent }";
                } else if (path.endsWith(".css")){
                    style = "body { background-image: url('background.jpg');background-repeat: no-repeat;background-attachment: fixed;background-size: cover; }";
                } else {
                    webpage = configManager.getIndexHtml();
                }
            }
        }

        SpringApplication app = new SpringApplication(App.class);
        app.setDefaultProperties(Collections.singletonMap("server.port", "25533"));
        app.run(args);

    }


    // background-image: url(\""+image_url+"\");background-repeat: no-repeat;background-position: left;padding-left: 250px;font-weight: bold;background-size: 100%;
}
