/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yt.downloader;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

    public static ConfigManager configManager;
    public static String webpage;


    public static void main(String[] args) {
        // ApplicationContext ctx = SpringApplication.run(App.class, args);

        try {
            configManager = new ConfigManager();
        } catch (Exception e) { e.printStackTrace(); }

        webpage = configManager.getIndexHtml();

        SpringApplication.run(App.class, args);

    }
}
